### ISSUE TITLE
Helen: 7: Helen: wmctrl: not found

### ISSUE THREAD

**Issue by RubenBaez** [swanux/helen#2]
**Description.**
When i execute ./Helen i got this error

`
Helen: 7: Helen: wmctrl: not found
`
![image](https://user-images.githubusercontent.com/13793894/53779226-67129680-3ecd-11e9-905b-78e159be3824.png)

**Comment by swanux** [comment]
### Thank you for your report!
**The reason:**
wmctrl is a separate package and depending on your distro and desktop environment maybe it isn't installed. 
**Solution:**
Run this command:
`sudo apt install wmctrl`

I'm already working on inbuilt dependency check and some other extra features and it will be fixed in the v0.1.9.
